services:
  agenda_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=balde
      - POSTGRES_PASSWORD=0710
      - POSTGRES_DB=agenda_angelica
    volumes:
      - data_db:/var/lib/postgresql/data

  web:
    build: .
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - agenda_db
    environment:
      - DATABASE_URL=postgresql://balde:0710@agenda_db:5432/agenda_angelica

volumes:
  data_db:
