"""Add verification code fields to users

Revision ID: 2bf58c2eba72
Revises: 90f725bcfbda
Create Date: 2025-06-07 21:49:08.380579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf58c2eba72'
down_revision = '90f725bcfbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_verificacao', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('validade_codigo', sa.DateTime(), nullable=True))
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('validade_codigo')
        batch_op.drop_column('codigo_verificacao')

    # ### end Alembic commands ###
