"""Adiciona password_hash como nullable

Revision ID: 6859e8083c0c
Revises: c7c804c0c36d
Create Date: 2025-05-04 17:59:32.366856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6859e8083c0c'
down_revision = 'c7c804c0c36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###
