"""Adiciona coluna observacoes à tabela agendamentos

Revision ID: 887e176d3ed7
Revises: 
Create Date: 2025-05-03 23:43:23.892071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887e176d3ed7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=14),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['cpf'])
        batch_op.create_unique_constraint(None, ['telefone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('endereco',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
