"""Adiciona password_hash ao usuário

Revision ID: c7c804c0c36d
Revises: 9429faa0e446
Create Date: 2025-05-04 13:37:21.484864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c804c0c36d'
down_revision = '9429faa0e446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
