"""empty message

Revision ID: fe14e3009e77
Revises: 8d499049f2da
Create Date: 2025-06-08 15:34:06.525852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe14e3009e77'
down_revision = '8d499049f2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_constraint('agendamentos_servico_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'servicos', ['servico_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('agendamentos_servico_id_fkey', 'servicos', ['servico_id'], ['id'])

    # ### end Alembic commands ###
